//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERP_AmericanTMartEntities : DbContext
    {
        public ERP_AmericanTMartEntities()
            : base("name=ERP_AmericanTMartEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OpeningBlance> OpeningBlances { get; set; }
        public virtual DbSet<ProductStockDetail> ProductStockDetails { get; set; }
        public virtual DbSet<ProductStockMaser> ProductStockMasers { get; set; }
    }
}
