//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpeningBlance
    {
        public int Id { get; set; }
        public string ProductId { get; set; }
        public string TransectionNo { get; set; }
        public string TransectionType { get; set; }
        public System.DateTime TransectionDate { get; set; }
        public decimal TransectionQty { get; set; }
        public decimal TransectionQtyPrev { get; set; }
        public decimal StockQty { get; set; }
        public decimal StockUnitPrice { get; set; }
        public decimal StockAmount { get; set; }
        public string CompanyId { get; set; }
        public string BranchId { get; set; }
        public string SupplierId { get; set; }
        public string BrandId { get; set; }
        public bool Active { get; set; }
        public bool Archive { get; set; }
        public bool IsSynchronized { get; set; }
        public bool IsUpdated { get; set; }
        public string SynchronizationType { get; set; }
        public string Remarks { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string AddedFromIp { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedFromIp { get; set; }
    }
}
