//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string Id { get; set; }
        public int Sequence { get; set; }
        public string Code { get; set; }
        public string SupplierProductCode { get; set; }
        public string Name { get; set; }
        public byte[] Picture { get; set; }
        public string ProductCategoryId { get; set; }
        public string ProductSubCategoryId { get; set; }
        public string ProductSubsidiaryCategoryId { get; set; }
        public string UOMId { get; set; }
        public string ColorId { get; set; }
        public string StyleId { get; set; }
        public string FlavorId { get; set; }
        public string GradeId { get; set; }
        public string FloorId { get; set; }
        public string RackId { get; set; }
        public string ManufacturerId { get; set; }
        public string VatCategoryId { get; set; }
        public string SizeId { get; set; }
        public string RAMId { get; set; }
        public string ROMId { get; set; }
        public string SupplierId { get; set; }
        public string BrandId { get; set; }
        public string CountryId { get; set; }
        public decimal PurchasePrice { get; set; }
        public decimal RetailPrice { get; set; }
        public decimal WholeSalePrice { get; set; }
        public decimal ProfitAmount { get; set; }
        public decimal ProfitAmountInPercentage { get; set; }
        public int ShelfLife { get; set; }
        public int ReorderLevel { get; set; }
        public decimal MaxDiscount { get; set; }
        public bool Active { get; set; }
        public bool Archive { get; set; }
        public bool IsSynchronized { get; set; }
        public bool IsUpdated { get; set; }
        public string SynchronizationType { get; set; }
        public string Description { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string AddedFromIp { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedFromIp { get; set; }
    }
}
