//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ProductStockMaser
    {        
        public string StockID { get; set; }
        public int BranchID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string ProductID { get; set; }
        public int CompanyID { get; set; }
        public int UOMID { get; set; }
        public decimal ReceiveQty { get; set; }
        public decimal ReceiveValue { get; set; }
        public Nullable<System.DateTime> LastReceiveDate { get; set; }
        public decimal IssueQty { get; set; }
        public decimal IssueValue { get; set; }
        public Nullable<System.DateTime> LastIssueDate { get; set; }
        public decimal CurrentRate { get; set; }
        public decimal CurrentStock { get; set; }
        public decimal CurrentValue { get; set; }
        public decimal SalesRate { get; set; }
        public decimal SalesValue { get; set; }
        public Nullable<System.DateTime> LastSalesDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreatePc { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatePc { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteOn { get; set; }
        public string DeletePc { get; set; }
    }
}
